### ISSUE TITLE
o-aside-panel floats above o-ft-header

### ISSUE THREAD

**Issue by richard-still-ft** [Financial-Times/o-aside-panel#1]
Add both the header and panel to a page, add enough content to the panel so that scrolling is required. Then scroll.

![screen shot 2014-05-20 at 09 16 42](https://cloud.githubusercontent.com/assets/2535456/3024336/f46c0722-dff6-11e3-9110-47c9c174bbcd.png)

**Comment by onishiweb** [comment]
Do you know if this is still an issue and if so is there somewhere we can see this happening?

**Comment by AlbertoElias** [comment]
We can close this, that was an extremely old version of header
