### ISSUE TITLE
Deprecate component?

### ISSUE THREAD

**Issue by gvonkoss** [Financial-Times/o-aside-panel#27]
There don't seem to be any products using this component (splunk query: `(app=origami-build-service-eu OR app=origami-build-service-us) "o-aside-panel"| table referer | dedup referer`)

**Comment by JakeChampion** [comment]
BitBucket -- http://git.svc.ft.com/plugins/servlet/search?q=o-aside-panel
GitHub -- https://github.com/search?utf8=%E2%9C%93&q=org%3AFinancial-Times+o-aside-panel&type=Code

**Comment by gvonkoss** [comment]
related to https://github.com/orgs/Financial-Times/projects/2#card-6972933
