### ISSUE TITLE
header margin affected by including o-ft-typography in the bundle

### ISSUE THREAD

**Issue by triblondon** [Financial-Times/o-aside-panel#5]
http://jsbin.com/culav/2/edit

![image](https://cloud.githubusercontent.com/assets/1735391/3919151/d7053730-23a3-11e4-8029-3c2f51620350.png)

The panel headers should have left padding.  Removing the typography module from the bundle makes the padding reappear:

![image](https://cloud.githubusercontent.com/assets/1735391/3919154/e4e9fb74-23a3-11e4-9959-c6189afd1774.png)

**Comment by AlbertoElias** [comment]
This has been fixed by the use of mixins. Will close
